export const Data = {
  characteristics: [
    {
      title: 'Сила',
      value: 10,
      mod: '+0',
    },
    {
      title: 'Ловкость',
      value: 16,
      mod: '+3',
    },
    {
      title: 'Выносливость',
      value: 12,
      mod: '+1',
    },
    {
      title: 'Интеллект',
      value: 12,
      mod: '+1',
    },
    {
      title: 'Мудрость',
      value: 10,
      mod: 0,
    },
    {
      title: 'Харизма',
      value: 18,
      mod: '+4',
    },
  ],
  savingThrows: [
    {
      title: 'Стойкость',
      mod: '+6',
    },
  ],
  skills: [
    {
      title: 'Акробатика',
      value: '+6',
      proficiency: '+3',
      characteristics: 'Ловкость',
    },
    {
      title: 'Атлетика',
      value: '+0',
      proficiency: '+0',
      characteristics: 'Сила',
    },
    {
      title: 'Воровство',
      value: '+3',
      proficiency: '+0',
      characteristics: 'Ловкость',
    },
  ],
  cantrips: [
    {
      title: 'Разрушение нежити',
      description:
        'Вы пронзаете цель энергией. Вы наносите позитивного урон равный 1d6 + ваш модификатор характеристики колдовства. Цель должна совершить простой спасбросок Стойкости. Если существо критически проваливает спасбросок, оно еще на 1 раунд получает состояние ',
      link: 'https://pf2e-ru-translation.readthedocs.io/ru/latest/spells/D/disrupt-undead.html?highlight=%D0%A0%D0%B0%D0%B7%D1%80%D1%83%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B5%D0%B6%D0%B8%D1%82%D0%B8#disrupt-undead-1',
    },
    {
      title: 'Электрическая дуга',
      description: '',
      link: 'https://pf2e-ru-translation.readthedocs.io/ru/latest/spells/E/electric-arc.html?highlight=%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D0%B4%D1%83%D0%B3%D0%B0#electric-arc-1',
    },
  ],
};

/*Data = {
characterData: {
  abp: false,
  addLevelToProficiency: true,
  age: 'Not set',
  alignment: 'N',
  allowHalfHeritages: false,
  allowMultiplePurchase: false,
  ancestry: 'Human',
  autoSave: true,
  background: 'BACKGROUND_Eidolon Contact',
  backgroundBoostLimitedSelection: 5,
  backgroundBoostThirdSelection: 4,
  characterLevel: 1,
  characterName: 'Veruma Esse',
  characterRef: 21,
  classKeyAbility: 5,
  className: 'Summoner',
  cloudStorage: false,
  copper: 0,
  currentHP: 70,
  damageTaken: 0,
  deity: 'Not set',
  deprecatedLanguagesSelection: 'Not set',
  dialects: [null, null, null, null, null, null],
  dualClassKeyAbility: -1,
  emailedBuildID: -1,
  experiencePoints: 0,
  freeArchetype: false,
  gender: 'Not set',
  getBackgroundBoostFreeSelection: 1,
  gold: 11,
  hashMapAbilityBoosts: {
    1: [1, 5, 2, 3],
    20: [],
    5: [],
    10: [],
    15: [],
  },
  hashMapActiveConditions: {},
  hashMapActiveCustomBuffs: {},
  hashMapAdditionalLores: {},
  hashMapAncestryFreeBoostSelections: {
    0: 5,
    1: 1,
  },
  hashMapBonusSpellPerDay: {},
  hashMapBonusSpellPrepared: {},
  hashMapBonusSpellSlots: {},
  hashMapCustomAbilityIncreases: {},
  hashMapCustomFeatChoices: {},
  hashMapCustomSkillIncreases: {},
  hashMapEquipmentContainers: {},
  hashMapFeatExtraSelections: {},
  hashMapFeatSelections: {
    'Evolution Feat 1': 'SUMMONER_Glider Form',
    'Summoner Feat 2': 'ARCHETYPE_Bard Dedication',
    'Heritage Feat': 'VERSATILE_Aasimar',
    'Natural Ambition Class FeatHuman Feat 1': 'SUMMONER_Dual Studies',
    'Human Feat 1': 'HUMAN_Natural Ambition',
  },
  hashMapFormulaBook: {},
  hashMapFormulaBookByCaster: {},
  hashMapKnownSpellsByCaster: {},
  hashMapPetData: {
    petEidolon: {
      hashMapAnimalSpecializations: {},
      hashMapEidolonAttacks: {
        0: {
          damageType: 'P',
          ref: 6,
          attackAbilityRef: 0,
          damageAbilityRef: 0,
          increasedDice: false,
          itemStriking: 0,
          listPropertyRunes: [],
          potency: 0,
          sizeChange: 0,
          weaponName: 'Horn',
          amount: 1,
          stowed: false,
        },
        1: {
          damageType: 'B',
          ref: 0,
          attackAbilityRef: 0,
          damageAbilityRef: 0,
          increasedDice: false,
          itemStriking: 0,
          listPropertyRunes: [],
          potency: 0,
          sizeChange: 0,
          weaponName: 'Wing',
          amount: 1,
          stowed: false,
        },
      },
      hashMapSelectedFamiliarAbilities: {},
      hashMapSelectedFamiliarResistances: {},
      hashMapSelectedFamiliarSkilled: {},
      incredibleType: 0,
      nickname: 'Unnamed',
      petName: 'Fey Eidolon',
      petType: 2,
      specificGainedLevel: 1,
      switchA: false,
      switchB: true,
      abp: false,
      addLevelToProficiency: true,
      age: 'Not set',
      alignment: 'N',
      allowHalfHeritages: false,
      allowMultiplePurchase: false,
      ancestry: 'Human',
      autoSave: true,
      background: 'BACKGROUND_Barkeep',
      backgroundBoostLimitedSelection: 2,
      backgroundBoostThirdSelection: 4,
      characterLevel: 1,
      characterName: 'Unknown Adventurer',
      characterRef: -1,
      classKeyAbility: 0,
      className: 'Fighter',
      cloudStorage: false,
      copper: 0,
      currentHP: 70,
      damageTaken: 0,
      deity: 'Not set',
      deprecatedLanguagesSelection: 'Not set',
      dialects: [null, null, null, null, null, null],
      dualClassKeyAbility: -1,
      emailedBuildID: -1,
      experiencePoints: 0,
      freeArchetype: false,
      gender: 'Not set',
      getBackgroundBoostFreeSelection: 0,
      gold: 15,
      hashMapAbilityBoosts: {},
      hashMapActiveConditions: {},
      hashMapActiveCustomBuffs: {},
      hashMapAdditionalLores: {},
      hashMapAncestryFreeBoostSelections: {},
      hashMapBonusSpellPerDay: {},
      hashMapBonusSpellPrepared: {},
      hashMapBonusSpellSlots: {},
      hashMapCustomAbilityIncreases: {},
      hashMapCustomFeatChoices: {},
      hashMapCustomSkillIncreases: {},
      hashMapEquipmentContainers: {},
      hashMapFeatExtraSelections: {},
      hashMapFeatSelections: {},
      hashMapFormulaBook: {},
      hashMapFormulaBookByCaster: {},
      hashMapKnownSpellsByCaster: {},
      hashMapPetData: {},
      hashMapPlayerSpells: {},
      hashMapRepertoireOverride: {},
      hashMapSignatureFormula: {},
      hashMapSignatureSpells: {},
      hashMapSignatureSpellsMultiple: {},
      hashMapSkillIncreases: {},
      hashMapSpecialSelections: {},
      hashMapSpontaneousSpellsCast: {},
      hashMapTrainedOnlySkillChoices: {},
      hashMapUsedInfusedReagentsByCaster: {},
      heroPoints: 1,
      ignoreFreeArcheAbilityReq: false,
      ignoreFreeArcheRest: false,
      listCurrentlyInactiveBuffs: [],
      listCustomLores: [],
      listDisabledRulebooks: [],
      listKnownSpells: [],
      listLanguages: [],
      listPlayerEquipment: [],
      listPlayerFormula: [],
      listPlayerWeapons: [],
      listSpentSpellSlots: [],
      listStowedPlayerArmor: [],
      listStowedPlayerShields: [],
      listUserBonusFeats: [],
      notes: 'Notes',
      otherCaster: false,
      platinum: 0,
      playerArmor: {
        armorName: 'Unarmored',
        armoredSkirt: false,
        itemResilient: 0,
        listPropertyRunes: [],
        potency: 0,
        worn: true,
        amount: 1,
        stowed: false,
      },
      separateAdventurersKit: true,
      shieldDamage: 0,
      showDedicationFeats: true,
      showLevelWarnings: true,
      showSpellbookConfirmation: false,
      silver: 0,
      spentResolve: 0,
      spentResonance: 0,
      spentSpellPoints: 0,
      staminaDamage: 0,
      temporaryHP: 0,
      useStamina: false,
      usedInfusedReagents: 0,
    },
  },
  hashMapPlayerSpells: {
    'Summoner\u00260\u00260': {
      heighten: 0,
      spellList: 3,
      spellName: 'Disrupt Undead',
    },
    'Summoner\u00260\u00261': {
      heighten: 0,
      spellList: 3,
      spellName: 'Prestidigitation',
    },
    'Summoner\u00261\u00260': {
      heighten: 0,
      spellList: 0,
      spellName: 'Color Spray',
    },
    'Eidolon\u00260\u00260': {
      heighten: 0,
      spellList: 3,
      spellName: 'Gouging Claw',
    },
    'Summoner\u00260\u00262': {
      heighten: 0,
      spellList: 3,
      spellName: 'Electric Arc',
    },
    'Summoner\u00261\u00261': {
      heighten: 0,
      spellList: 3,
      spellName: 'Ventriloquism',
    },
    'Summoner\u00260\u00263': {
      heighten: 0,
      spellList: 3,
      spellName: 'Stabilize',
    },
    'Eidolon\u00260\u00261': {
      heighten: 0,
      spellList: 3,
      spellName: 'Tame',
    },
    'Summoner\u00260\u00264': {
      heighten: 0,
      spellList: 3,
      spellName: 'Tanglefoot',
    },
  },
  hashMapRepertoireOverride: {},
  hashMapSignatureFormula: {},
  hashMapSignatureSpells: {},
  hashMapSignatureSpellsMultiple: {},
  hashMapSkillIncreases: {
    1: [],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
  },
  hashMapSpecialSelections: {
    'BACKGROUND_Eidolon Contact': {
      'Select Eidolon Lore': 'Fey Eidolon',
    },
    'Dual Studies': {
      'Select Eidolon Skill': 'Intimidation',
      'Select Summoner Skill': 'Acrobatics',
    },
    Eidolon: {
      'Select Eidolon Type': 'Fey Eidolon',
    },
  },
  hashMapSpontaneousSpellsCast: {
    Summoner: {
      1: 0,
    },
  },
  hashMapTrainedOnlySkillChoices: {
    'Summoner Feat 21': ['Society'],
    'BACKGROUND_Eidolon Contact': ['Religion'],
    'Summoner Feat 2': ['Occultism'],
    standardSelection: ['Diplomacy', 'Performance', 'Stealth', 'Medicine'],
  },
  hashMapUsedInfusedReagentsByCaster: {},
  heroPoints: 1,
  ignoreFreeArcheAbilityReq: false,
  ignoreFreeArcheRest: false,
  listCurrentlyInactiveBuffs: [],
  listCustomLores: [],
  listDisabledRulebooks: [
    'The Slithering',
    'Hellknight Hill',
    'Night of the Gray Death',
    'Against the Scarlet Triad',
    'Legacy of the Lost God',
    'Broken Promises',
    'Troubles in Otari',
    'AP 167',
    'AP 166',
    'AP 169',
    'AP 168',
    'Fists of the Ruby Phoenix Player\u0027s Guide',
    'Malevolence',
    'PSS 17',
    'Cult of Cinders',
    'PSS 10',
    'Strength of Thousands Player\u0027s Guide',
    'Lord of the Black Sands',
    'The Fall of Plaguestone',
    'AP 170',
    'AP 172',
    'AP 171',
    'Agents of Edgewatch',
    'AP 173',
    'Extinction Curse Player\u0027s Guide',
    'AP 158',
    'AP 157',
    'The Show Must Go On',
    'AP 159',
    'PSS 5',
    'PSS 2',
    'PSS 1',
    'The Apocalypse Prophet',
    'AP 161',
    'AP 160',
    'AP 163',
    'AP 162',
    'Little Trouble in Big Absalom',
    'AP 165',
    'AP 164',
    'Azarketi Ancestry Web Supplement',
    'Fires of the Haunted City',
    'Tomorrow Must Burn',
    'Age of Ashes',
    'Fumbus',
    'Abomination Vaults Player\u0027s Guide',
    'Siege of the Dinosaurs',
    'Life\u0027s Long Shadow',
    'Battlezoo Bestiary',
  ],
  listKnownSpells: [],
  listLanguages: [],
  listPlayerEquipment: [
    {
      invested: true,
      name: 'Bolts',
      quantity: 10,
      amount: 1,
      stowed: false,
    },
  ],
  listPlayerFormula: [],
  listPlayerWeapons: [
    {
      attackAbilityRef: 1,
      damageAbilityRef: 0,
      increasedDice: false,
      itemStriking: 0,
      listPropertyRunes: [],
      potency: 0,
      sizeChange: 0,
      weaponName: 'Crossbow',
      amount: 1,
      stowed: false,
    },
  ],
  listSpentSpellSlots: [],
  listStowedPlayerArmor: [],
  listStowedPlayerShields: [],
  listUserBonusFeats: [],
  notes: 'Notes',
  otherCaster: false,
  platinum: 0,
  playerArmor: {
    armorName: 'Explorer\u0027s Clothing',
    armoredSkirt: false,
    itemResilient: 0,
    listPropertyRunes: [],
    potency: 0,
    worn: true,
    amount: 1,
    stowed: false,
  },
  separateAdventurersKit: true,
  shieldDamage: 0,
  showDedicationFeats: true,
  showLevelWarnings: true,
  showSpellbookConfirmation: false,
  silver: 8,
  spentResolve: 0,
  spentResonance: 0,
  spentSpellPoints: 0,
  staminaDamage: 0,
  temporaryHP: 0,
  useStamina: false,
  usedInfusedReagents: 0,
},
listCustomFiles: [],
};
*/
